modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "MIT"
issueTrackerURL = "https://github.com/Khajiitos/WorldPlayTime/issues"

[[mods]]
modId = "worldplaytime"
version = "${version}"
logoFile="icon.png"
displayName = "World Play Time"
authors = "Khajiitos"
displayURL = "https://github.com/Khajiitos/WorldPlayTime"
description = '''Displays the world's play time in the world selection menu.'''
updateJSONURL = "https://updates.khajiitos.fun/world-play-time/updates-forge.json"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.worldplaytime]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.worldplaytime]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
